name: ordering-signalrhub CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/ordering-signalrhub/**' # Branches containing feature/ in the name
      - 'bugfix/ordering-signalrhub/**' # Branches containing bugfix/ in the name
      - 'hotfix/ordering-signalrhub/**' # Branches containing hotfix/ in the name
      - 'release/ordering-signalrhub/**' # Branches containing release/ in the name
      - 'refactor/ordering-signalrhub/**' # Branches containing refactor/ in the name
      - 'test/ordering-signalrhub/**' # Branches containing test/ in the name
      - 'techdebt/ordering-signalrhub/**' # Branches containing techdebt/ in the name
    paths:
      - src/BuildingBlocks/**
      - src/Services/Ordering/**
      - .github/workflows/ordering-signalrhub.yml

  pull_request: # Trigger the workflow on pull requests
    branches:
      - main
    paths:
      - src/BuildingBlocks/**
      - src/Services/Ordering/**
      - .github/workflows/ordering-signalrhub.yml

env:
  SERVICE: ordering-signalrhub
  IMAGE: ordering.signalrhub

jobs:
  ordering-signalrhub-ci:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/workflows/composite/build
        with:
          service: ${{ env.SERVICE }}
          # registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}

  # BuildLinux:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name != 'pull_request' }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - uses: ./.github/workflows/composite/build-push
  #       with:
  #         service: ${{ env.SERVICE }}
  #         registry_host: ${{ secrets.REGISTRY_HOST }}
  #         # registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
  #         image_name: ${{ env.IMAGE }}
  #         registry_username: ${{ secrets.USERNAME }}
  #         registry_password: ${{ secrets.PASSWORD }}
