name: webhooks-api CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/webhooks-api/**' # Branches containing feature/ in the name
      - 'bugfix/webhooks-api/**' # Branches containing bugfix/ in the name
      - 'hotfix/webhooks-api/**' # Branches containing hotfix/ in the name
      - 'release/webhooks-api/**' # Branches containing release/ in the name
      - 'refactor/webhooks-api/**' # Branches containing refactor/ in the name
      - 'test/webhooks-api/**' # Branches containing test/ in the name
      - 'techdebt/webhooks-api/**' # Branches containing techdebt/ in the name
    paths:
      - src/BuildingBlocks/**
      - src/Services/Webhooks/**
      - .github/workflows/webhooks-api.yml

  pull_request: # Trigger the workflow on pull requests
    branches:
      - main
    paths:
      - src/BuildingBlocks/**
      - src/Services/Webhooks/**
      - .github/workflows/webhooks-api.yml

env:
  SERVICE: webhooks-api
  IMAGE: webhooks.api

jobs:
  BuildContainersForPR_Linux:
    runs-on: ubuntu-latest
    # if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/workflows/composite/build
        with:
          service: ${{ env.SERVICE }}
          # registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}

  # BuildLinux:
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event_name != 'pull_request' }}
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #   - uses: ./.github/workflows/composite/build-push
  #     with:
  #       service: ${{ env.SERVICE }}
  #       registry_host: ${{ secrets.REGISTRY_HOST }}
  #       # registry_endpoint: ${{ secrets.REGISTRY_ENDPOINT }}
  #       image_name: ${{ env.IMAGE }}
  #       registry_username: ${{ secrets.USERNAME }}
  #       registry_password: ${{ secrets.PASSWORD }}
