name: webstatus CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/webstatus/**' # Branches containing feature/ in the name
      - 'bugfix/webstatus/**' # Branches containing bugfix/ in the name
      - 'hotfix/webstatus/**' # Branches containing hotfix/ in the name
      - 'release/webstatus/**' # Branches containing release/ in the name
      - 'refactor/webstatus/**' # Branches containing refactor/ in the name
      - 'test/webstatus/**' # Branches containing test/ in the name
      - 'techdebt/webstatus/**' # Branches containing techdebt/ in the name
    paths:
      - src/BuildingBlocks/**
      - src/Web/WebStatus/**
      - .github/workflows/webstatus.yml

  pull_request: # Trigger the workflow on pull requests
    branches:
      - main
    paths:
      - src/BuildingBlocks/**
      - src/Web/WebStatus/**
      - .github/workflows/webstatus.yml

env:
  SERVICE: webstatus
  IMAGE: webstatus

jobs:
  webstatus-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/workflows/composite/build
        with:
          service: ${{ env.SERVICE }}
